### PR TITLE
Enable datepicker with 0.6.0 version

### PR DESCRIPTION
**Pull request by JorritPosthuma**
I disabled it previously because it broke 😊. With 0.6.0 it’s working again! So lets show @supnate his work :D

### CODE REVIEW

**Comment by dcousens** [comment]
ACK, I'll leave this up to @JedWatson

**Comment by JedWatson** [comment]
:+1:

**Comment by JedWatson** [comment]
Thanks @JorritPosthuma and @supnate - this is now live on http://touchstonejs.io :grinning:

**Comment by supnate** [comment]
Thanks @JedWatson , I've been looking forward to it for long, lol:D

**Pull request merged**
